import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProgressBar from "@/components/next-progress-bar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PDsteF",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProgressBar/>
        {children}</body>
    </html>
  );
}
